name: /Users/pfseaho/Downloads/Python/sanal_ressam_projesi/env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py311hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.4.0
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mediapipe==0.10.9
      - numpy==1.26.4
      - opencv-contrib-python==4.9.0.80
      - pillow==12.1.1
      - protobuf==3.20.3
      - pycparser==3.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - sounddevice==0.5.5